// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzaDUcHjAOHjblvSQ7ihvcOImjAYoPMqg',
    appId: '1:23870101060:web:43d4db20b2804a9a1c4e11',
    messagingSenderId: '23870101060',
    projectId: 'kineticlync',
    authDomain: 'kineticlync.firebaseapp.com',
    storageBucket: 'kineticlync.appspot.com',
    measurementId: 'G-80N1RFKEKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz0mGzEJOtDPLArVH2ilYvoOxARdQzMSc',
    appId: '1:23870101060:android:1902c3079dd1a4861c4e11',
    messagingSenderId: '23870101060',
    projectId: 'kineticlync',
    storageBucket: 'kineticlync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFRTXnmCMLkqmYIbLDhcVG9LsEmcPjqFw',
    appId: '1:23870101060:ios:7403ebd1356777e91c4e11',
    messagingSenderId: '23870101060',
    projectId: 'kineticlync',
    storageBucket: 'kineticlync.appspot.com',
    iosBundleId: 'com.example.kineticLync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFRTXnmCMLkqmYIbLDhcVG9LsEmcPjqFw',
    appId: '1:23870101060:ios:9a5ec8e43c496bef1c4e11',
    messagingSenderId: '23870101060',
    projectId: 'kineticlync',
    storageBucket: 'kineticlync.appspot.com',
    iosBundleId: 'com.example.kineticLync.RunnerTests',
  );
}
